GRAVITY_MS2 = 9.81
AREA_OF_PISTON = 0.00125
FT_TO_M = 0.3048

# MATERIALS
OAK = 0
ALUMINUM = 1
PAPER = 2
STAINLESS_STEEL = 3
POLYSTYRENE = 4

# SHAPES
CUBE = 0
SPHERE = 1
CYLINDER = 2
CONE = 3

# DENSITIES
# https://amesweb.info/Materials/Density-Materials.aspx
OAK_DENSITY_KGM3 = 690
ALUMINUM_DENSITY_KGM3 = 2700
PAPER_DENSITY_KGM3 = 700
STAINLESS_STEEL_DENSITY_KGM3 = 585
POLYSTYRENE_DENSITY_KGM3 = 920

DENSITIES = [OAK_DENSITY_KGM3, ALUMINUM_DENSITY_KGM3, PAPER_DENSITY_KGM3,
             STAINLESS_STEEL_DENSITY_KGM3, POLYSTYRENE_DENSITY_KGM3]
